# Generated by Django 3.2.9 on 2022-04-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotenft',
            name='blockchain',
        ),
        migrations.RemoveField(
            model_name='promotenft',
            name='image',
        ),
        migrations.RemoveField(
            model_name='promotenft',
            name='link',
        ),
        migrations.RemoveField(
            model_name='promotenft',
            name='marketplace',
        ),
        migrations.RemoveField(
            model_name='promotenft',
            name='title',
        ),
    ]
