# Generated by Django 3.2.9 on 2022-04-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220410_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoteNft',
        ),
    ]
