# Generated by Django 3.2.9 on 2022-04-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_promotenft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newevent',
            name='dropdown',
        ),
        migrations.DeleteModel(
            name='DropPromote',
        ),
    ]
