# Generated by Django 3.2.9 on 2022-04-12 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220410_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newevent',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='newevent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
