# Generated by Django 3.2.9 on 2022-04-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_newevent_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='block',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
