# Generated by Django 3.2.9 on 2022-04-13 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_blockchain_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='block',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='market',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
