# Generated by Django 3.2.9 on 2022-04-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220413_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='link',
            field=models.CharField(max_length=10000),
        ),
    ]
