# Generated by Django 3.2.9 on 2022-04-14 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_newevent_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='blockchain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.blockchain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newevent',
            name='marketplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.marketplace'),
            preserve_default=False,
        ),
    ]
