# Generated by Django 3.2.9 on 2022-04-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_newevent_blockchain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='blockchain',
            field=models.ForeignKey(default='CHOOSE BLOCKCHAIN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.blockchain'),
        ),
    ]
