# Generated by Django 3.2.9 on 2022-04-16 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_newevent_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevent',
            name='discord',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newevent',
            name='twiter',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newevent',
            name='website',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
