# Generated by Django 3.2.9 on 2022-04-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220416_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
