# Generated by Django 3.2.9 on 2022-05-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220516_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='block',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='market',
            field=models.CharField(max_length=10000),
        ),
    ]
