# Generated by Django 3.2.9 on 2022-04-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DropPromote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PromoteNft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=60)),
                ('link', models.TextField()),
                ('blockchain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.blockchain')),
                ('dropdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.droppromote')),
                ('marketplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.marketplace')),
            ],
        ),
    ]
