# Generated by Django 3.2.9 on 2022-04-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20220410_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blockchain',
            new_name='BlockchainPromo',
        ),
        migrations.RenameModel(
            old_name='Marketplace',
            new_name='MarketplacePromo',
        ),
        migrations.RenameModel(
            old_name='PromoteNft',
            new_name='PromoteNftPromo',
        ),
    ]
