# Generated by Django 3.2.9 on 2022-04-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20220410_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchainpromo',
            old_name='block',
            new_name='blockp',
        ),
        migrations.RenameField(
            model_name='marketplacepromo',
            old_name='market',
            new_name='marketp',
        ),
    ]
