# Generated by Django 3.2.9 on 2022-04-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_auto_20220413_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotenftpromo',
            name='link',
            field=models.CharField(max_length=10000),
        ),
    ]
