# Generated by Django 3.2.9 on 2022-04-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0008_alter_promotenftpromo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainpromo',
            name='blockp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplacepromo',
            name='marketp',
            field=models.CharField(max_length=20),
        ),
    ]
