# Generated by Django 3.2.9 on 2022-04-16 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0010_auto_20220415_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotenftpromo',
            name='discord',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotenftpromo',
            name='twiter',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotenftpromo',
            name='website',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
