# Generated by Django 3.2.9 on 2022-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0012_alter_promotenftpromo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotenftpromo',
            name='discord',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='promotenftpromo',
            name='twiter',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='promotenftpromo',
            name='website',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
