# Generated by Django 3.2.9 on 2022-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0013_auto_20220419_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainpromo',
            name='blockp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='marketplacepromo',
            name='marketp',
            field=models.CharField(max_length=200),
        ),
    ]
