# Generated by Django 3.2.9 on 2022-05-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0014_auto_20220516_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainpromo',
            name='blockp',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='marketplacepromo',
            name='marketp',
            field=models.CharField(max_length=10000),
        ),
    ]
