# Generated by Django 3.2.9 on 2022-05-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0015_auto_20220516_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ad', models.ImageField(upload_to='')),
                ('title_ad', models.CharField(max_length=500)),
                ('url_ad', models.CharField(max_length=10000)),
            ],
        ),
    ]
